server:  
  port: 8888  

eureka:  
  instance:   
    hostname: peer2 #Eureka实例的主机名 
    instance-id: ${spring.application.name}:${server.port}
  client:  
    service-url:  
      defaultZone: http://${security.user.name}:${security.user.password}@peer1:7777/eureka,http://${security.user.name}:${security.user.password}@peer3:9999/eureka